### ISSUE TITLE
Consider making `validate` an async function

### ISSUE THREAD

**Issue by blaine-arcjet** [arcjet/arcjet-js#1391]
> It feels like `validate` is where we should check if the body is available but I think it's sync which makes it impossible 🤦 We might revisit that in the future.

We may want to revisit the API of validate in entirety. For example, if you called `getBody()` inside it, how would you access the body in `protect()`?

_Originally posted by @blaine-arcjet in https://github.com/arcjet/arcjet-js/pull/1300#discussion_r1723961227_

**Comment by blaine-arcjet** [comment]
See also: #1520

**Comment by blaine-arcjet** [comment]
I looked into this a bit and it needs more work than just making it an async function because we can't assert the validation via TypeScript.

I think we're going to want to return a value that is the details passed to `protect()` but I didn't get very far on that work before stashing it.

**Comment by e-moran** [comment]
Discussed this with @blaine-arcjet on a call today.

We have decided not to go ahead with this change. This was for a few reasons:
- Making `validate` async is incompatible with its current main purpose, because you cannot use `asserts` syntax with a function that returns a Promise. 
- One of the main motivations behind the change was so that we could call `getBody()` for sensitive info in the validate step to ensure that the body exists before we run protect. However you can only call `getBody()` once, so you would need to always pass the response from validate as input to protect.
- Making the change wouldn't provide any tangible user benefit in the sensitive info case because for local rules we call it immediately before calling `protect`.

The only case where there would be user benefit is when we could validate certain attributes before sending them to the server, such as the ability to generate a fingerprint from the provided characteristics. To address we are proposing an async `toProtocol` function when converting the request to the protocol, we could perform these validations there.

However, that change wouldn't be a breaking change so we don't need to include it in the pre-beta work.
