### ISSUE TITLE
Use kebab-case instead of SCREAMING_SNAKE_CASE for our string unions

### ISSUE THREAD

**Issue by blaine-arcjet** [arcjet/arcjet-js#1835]
This will better align us with jco bindings.

We also want to support SCREAMING_SNAKE_CASE during a deprecation period.

**Comment by e-moran** [comment]
Will the deprecation period end when the beta begins?

Also how do we want to handle outputs that are currently in `SCREAMING_SNAKE_CASE`, eg detected pii entities and bot types. Its easy to support both inputs for the transition period, but for outputs its a bit tricker. We could convert back to screaming snake case when its detected for inputs but someone could just specify `allow: []` and then its ambiguous.

**Comment by blaine-arcjet** [comment]
> Will the deprecation period end when the beta begins?

I believe it'll be when we go RC.

I think the deprecation period is also marked as breaking for the cases you stated. We can only easily produce backwards compatibility for inputs but it is harder for outputs (we'd have to duplicate all values in both formats). TypeScript will help guide most people for the migrations.

**Comment by e-moran** [comment]
> > Will the deprecation period end when the beta begins?
> 
> I believe it'll be when we go RC.
> 
> I think the deprecation period is also marked as breaking for the cases you stated. We can only easily produce backwards compatibility for inputs but it is harder for outputs (we'd have to duplicate all values in both formats). TypeScript will help guide most people for the migrations.

Do you think it would be bad to just support backwards compatibility for inputs, because we can't do it consistently for outputs?

It would probably make users take the breaking change more seriously if we don't support it for outputs at all, so there's less likely to be issues for users in cases where we can't infer the casing scheme that they want.

**Comment by e-moran** [comment]
Pausing work on this while we await a response on https://github.com/bytecodealliance/jco/issues/509

**Comment by e-moran** [comment]
It seems like jco will not allow us to make this change. This leaves us with three options:
1. We make the breaking change.
2. We do nothing, and leave the current translation layer as is.
3. We attempt to "fix" the generated bindings programmatically using a post-jco script.

We discussed why option one is unfavorable before, basically we would rather not force a breaking change on users where it isn't necessary.

Option three should work in theory, all of the string-enums that jco generates are either objects with a `tag` field or string unions. These can be identified programmatically and re-cased, however I could see this breaking at some point if jco makes changes.

I would like to make a decision on this soon so that we can progress the beta release.

cc @davidmytton

**Comment by davidmytton** [comment]
Agreed with your assessment. Option 3 sounds like it could break in the future so I suggest we stick with how it is now (option 2).

**Comment by e-moran** [comment]
Since we have decided not to make this change, I am closing this issue. Future work that would allow us to remove the translation layer is tracked by #2660.

**Comment by davidmytton** [comment]
Follow-up from [bytecodealliance/jco#1927](https://github.com/bytecodealliance/jco/pull/1927) (via [#2660](https://github.com/arcjet/arcjet-js/issues/2660)): we checked whether that flag would let us drop the translation layer. **It would not.**

## What #1927 adds

Still open (merge queue). New opt-in only:

- CLI: `--enum-values-screaming-snake-case`
- JS: `enumValuesScreamingSnakeCase: true`

It runs heck `to_shouty_snake_case` on **WIT enum case strings** in lift/lower and generated `.d.ts`. Default stays kebab. Docs say it does **not** apply to variants.

Example from the PR: `'value-a' | 'http-error'` → `'VALUE_A' | 'HTTP_ERROR'`.

## What we translate today

The public API is string unions (`"EMAIL"`, `"PHONE_NUMBER"`, `"DISPOSABLE"`). The jco bindings we remap are **variants**:

| Binding | Kind | Generated form |
|---|---|---|
| `SensitiveInfoEntity` | variant | `{ tag: "email" \| "phone-number" \| "ip-address" \| "credit-card-number" \| "custom" }` |
| `SensitiveInfoEntities` | variant | `{ tag: "allow" \| "deny" }` |
| `BotConfig` | variant | `{ tag: "allowed-bot-config" \| "denied-bot-config" }` |
| `EmailValidationConfig` | variant | `{ tag: "allow-email-validation-config" \| ... }` |
| `EmailValidity` | enum | `"valid" \| "invalid"` |
| email override | enum | `"yes" \| "no" \| "unknown"` |
| bot verify | enum | `"verified" \| "spoofed" \| "unverifiable"` |

The functions this issue / #2660 are about convert **string ↔ `{ tag }`**, then recase:

- `protocolSensitiveInfoEntitiesToAnalyze` / `analyzeSensitiveInfoEntitiesToString` in `arcjet/src/index.ts`
- `userEntitiesToWasm` / `wasmEntitiesToString` in `redact/src/index.ts`
- `toAnalyzeEntity` / `fromAnalyzeEntity` in `sensitive-info-rampart/src/entities.ts`

`SensitiveInfoEntity` **cannot** become a WIT enum: the `custom` case carries `val: string`. Enums have no payloads.

Email types (`DISPOSABLE`, `FREE`, …) already cross the Wasm boundary as `string[]` in screaming case. No translation there.

## Enabling the flag would add work, not remove it

The WIT enums we actually generate are internal and already kebab (`"yes"` / `"unknown"` / `"unverifiable"`, plus `result.validity === "valid"`). Turning the flag on would require `YES` / `UNKNOWN` / `UNVERIFIABLE` / `VALID` and would not delete any of the sensitive-info adapters.

## We also cannot pick this up as a one-line jco bump

- Pinned at `@bytecodealliance/jco@1.5.0` via `renovate.json` `allowedVersions: "<=1.5.0"` because of [jco#500](https://github.com/bytecodealliance/jco/issues/500) (componentize supply chain / package bloat).
- Latest published jco is `1.30.0`. #1927 would ship after that.
- [#5102](https://github.com/arcjet/arcjet-js/issues/5102) to switch to `@bytecodealliance/jco-transpile` was closed: WASI shim injection, `process.env` debug, Promise shimming, weaker types.

## What would actually close #2660

This matches the three options from earlier in this thread:

1. A jco option for **variant tags** (not in #1927). That would align `phone-number` → `PHONE_NUMBER` on `{ tag }`. We would still wrap/unwrap strings unless the public API became tagged unions.
2. Post-process generated bindings — already rejected here as too brittle (option 3).
3. Break the public API to kebab — already rejected here (option 1).

**Recommendation:** leave this issue and #2660 closed. #1927 is useful for real WIT enums, but it does not cover variant tags, which is the layer we still own. Do not bump jco for this flag alone. If jco ever grows the same option for variant tags we would get tag-name alignment, but we would still need the string↔variant adapter.
